name: Update Profile

on:
  schedule:
    - cron: '47 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Update Profile Readme
        uses: leoweyr/github-profile-readme-postprocessor@develop
        with:
          github_token: ${{ secrets.APP_GITHUB_TOKEN }}
          readme_template_path: 'template/README.template.md'
          tasks: |
            [
              {
                "anchor": "<!-- SUPPORT_INFO -->",
                "endpoint": "/v1/support/markdown",
                "params": {}
              },
              {
                "anchor": "<!-- CONTRIBUTION_FEATURES -->",
                "endpoint": "/v1/contributed-repositories/markdown",
                "params": {
                  "username": "leoweyr",
                  "title": "### ⚡ Features",
                  "limit_count": 3,
                  "include_commits": true,
                  "repository_topic_contains_any" : "plugin,script,minecraft,github"
                }
              },
              {
                "anchor": "<!-- CONTRIBUTION_PRODUCT -->",
                "endpoint": "/v1/contributed-repositories/markdown",
                "params": {
                  "username": "leoweyr",
                  "title": "### 📦️ Product",
                  "limit_count": 3,
                  "include_commits": true,
                  "repository_topic_contains_any" : "visual-editor,personal-website"
                }
              },
              {
                "anchor": "<!-- CONTRIBUTION_WHEEL -->",
                "endpoint": "/v1/contributed-repositories/markdown",
                "params": {
                  "username": "leoweyr",
                  "title": "### ⚙️ Wheel",
                  "limit_count": 3,
                  "include_commits": true,
                  "repository_name_contains_any": "react,engine,nodejs,python",
                  "repository_topic_contains_any" : "scaffold,framework"
                }
              },
              {
                "anchor": "<!-- CONTRIBUTION_SPECIFICATION -->",
                "endpoint": "/v1/contributed-repositories/markdown",
                "params": {
                  "username": "leoweyr",
                  "title": "### 📜 Specification",
                  "limit_count": 3,
                  "include_commits": true,
                  "repository_name_contains_any": "spec"
                }
              }
            ]

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          git commit -m "⚡ Auto update profile at ${TIMESTAMP}" || exit 0
          git push
